### ISSUE TITLE
yarn start error after pull latest on develop

### ISSUE THREAD

**Issue by wuyuyue** [nervosnetwork/neuron#153] opened 2019-03-19 07:11 UTC
![image](https://user-images.githubusercontent.com/40381396/54586857-3b5ce800-4a59-11e9-9558-c55945926ab2.png)

**Comment by Keith-CY** [comment] 2019-03-27 02:10
Is this problem fixed? @xiaoluSF

**Comment by xiaoluSF** [comment] 2019-03-27 02:31
@Keith-CY 
This error is caused by local build cache. 
Ash said just clean the cache by self instead other operation.
You can close this issue.

**Closed** 2019-03-27 02:35 UTC
