### ISSUE TITLE
Same wallet has different tx histories despite a full node sync 

### ISSUE THREAD

**Issue by James-Sangalli** [nervosnetwork/neuron#1619] opened 2020-05-09 23:46 UTC
I have 3 different wallets that have different balances, 2 of them have been swept and have zero funds in the nervos DAO.

The UI shows my nervos dao history for all 3 wallets rolled into one when in reality only one of the keys has the nervos dao deposits. This results in confusion as I cannot tell which wallet actually holds the deposit.

**Comment by Keith-CY** [comment] 2020-05-11 01:53
I'm not quite sure about the issue, does `all 3 wallets rolled into one` mean that every wallet has the same deposit history?

**Comment by James-Sangalli** [comment] 2020-05-11 22:28
@Keith-CY I forgot the password for one of them so I imported the same key again yet get different transaction histories (some same others missing) the node is in full sync too... Must just be a UI bug

**Comment by James-Sangalli** [comment] 2020-05-11 22:28
You might be able to reproduce with the following:

- have a wallet set that you already use
- reimport the same seed but name it differently 
- compare transaction history between the two identical wallets

**Comment by Keith-CY** [comment] 2020-05-13 02:31
According to the update of the issue, the actual bug is `the two wallets should have the same tx history but they don't`, am I right?

**Comment by James-Sangalli** [comment] 2020-05-13 03:16
@Keith-CY yes, the two wallets are exactly the same (derived from the same seed) but have different histories despite a full node sync

**Comment by Keith-CY** [comment] 2020-05-13 03:42
I've noticed that the issue is related to Neuron@v0.29.0, while the latest one is [Neuron@v0.30.0-rc2](https://github.com/nervosnetwork/neuron/releases/tag/v0.30.0-rc2).

It's a pre-release and the formal one will be released on May. 18. It has huge improvements on synchronization against v0.29.0.

Would you mind trying it with the new one to check if the error still exists?

**Closed** 2021-02-18 02:17 UTC
