### ISSUE TITLE
 0.36.0 update 0.100.1 update sync problem 'Block Synced 0% 0/0 Connecting'

### ISSUE THREAD

**Issue by bessamc** [nervosnetwork/neuron#2131] opened 2021-10-06 13:16 UTC
I had Neuron Wallet 0.36.0, running Notebook Acer Aspire E1-571-6824 Windows 8.1 x64 with no problems, I update Neuron Wallet 0.100.1, and now when I open the Wallet appear Block Synced 0% 0/0 Connecting. 
I got wallet working this way serveral times nothing changes.
[neuron_debug_1633520538201.zip](https://github.com/nervosnetwork/neuron/files/7294104/neuron_debug_1633520538201.zip)

**Comment by kellyshang** [comment] 2021-10-08 08:08
Hi @drgrib, your problem is caused by the ckb-indexer process didn't quit when close the Neuron, we will try to fix this problem in next version.
For now you can mannually quit the ckb-indexer in Activity Monitor then restart the Neuron.

**Comment by kellyshang** [comment] 2021-10-08 08:09
> Same issue for a fresh install of 0.100.1 on a MacBook Pro (16-inch, 2019) running macOS 11.6. Finished first full sync a few hours ago. Quit the program and opened it again to ensure full sync and it has just been sitting on `Sync not started yet` with `Block Synced 0% 0/0` for over 30 minutes. [neuron_debug_1633618345723.zip](https://github.com/nervosnetwork/neuron/files/7304761/neuron_debug_1633618345723.zip)

Hi @drgrib, your problem was caused by the ckb-indexer process didn't quit when close the Neuron, we will try to fix this problem in next version.
For now you can mannually quit the ckb-indexer in Activity Monitor then restart the Neuron.

**Comment by kellyshang** [comment] 2021-11-25 03:55
Will close this issue since there is no news. You can reopen this issue if there is any problem.

**Closed by kellyshang** 2021-11-25 03:55 UTC
