### ISSUE TITLE
Connexion fail after upgrade to v0.114.2

### ISSUE THREAD

**Issue by BouleChina** [nervosnetwork/neuron#3100] opened 2024-04-02 12:19 UTC
### Topic Type

Cannot Synchronize

### Detail of the issue

I use Neuron for months and everything was going well. Yesterday I saw there was an upgrade so I installed it. Now Neuron launch but seem to fail in connecting to mainnet
[bundled-ckb.log](https://github.com/nervosnetwork/neuron/files/14836506/bundled-ckb.log)
[bundled-ckb-lignt-client-mainnet.log](https://github.com/nervosnetwork/neuron/files/14836508/bundled-ckb-lignt-client-mainnet.log)
[main.log](https://github.com/nervosnetwork/neuron/files/14836509/main.log)
[status.json](https://github.com/nervosnetwork/neuron/files/14836510/status.json)

**Comment by Keith-CY** [comment] 2024-04-02 17:43
Hi @BouleChina 

This issue was caused by data incompatibility of the built-in full node and can be resolved by the following steps:

1. Keep Neuron off;
2. Open an application named **Windows PowerShell**, which should be a built-in app of Windows;
3. type **C:\Users\Boss\AppData\Local\Programs\Neuron\bin\ckb.exe migrate -C C:\Users\Boss\AppData\Roaming\Neuron\chains\mainnet** and hit <kbd>Enter</kbd> to start a data migration;
4. Data migration will requset confirmation, type **YES** and hit <kbd>Enter</kbd> to confirm;
5. Data migration should start and is expected to be done in 20 mins;
6. Start Neuron again and the synchronization should be recovered.

**Comment by BouleChina** [comment] 2024-04-03 09:38
Hi. It took about 3hours to migrate but now it works again. Thank you

**Closed** 2024-04-03 09:44 UTC
Labels: replied
