### ISSUE TITLE
Wallet memory usage shoots up to 30Gb

### ISSUE THREAD

**Issue by tantommy** [nervosnetwork/neuron#2183] opened 2021-11-24 20:57 UTC
When I go to History > *expand transaction* > Detail the wallet memory usage shoots up to 30Gb sometimes

![image](https://user-images.githubusercontent.com/7282254/143311812-ec07a344-fcd1-4b06-be0b-acf6071f4bfe.png)

**Comment by kellyshang** [comment] 2021-11-25 03:44
@tantommy Can you expand the process and take a fully screenshot of Neuron process? 
for example: 
![image](https://user-images.githubusercontent.com/28836185/143376158-3f66e7d8-35d0-47d8-bc93-eeee63375133.png)

**Comment by tantommy** [comment] 2021-11-25 04:11
> @tantommy Can you expand the process and take a fully screenshot of Neuron process? for example
![image](https://user-images.githubusercontent.com/7282254/143378426-47c66665-c76a-467c-bbbd-3e64d641568e.png)
![image](https://user-images.githubusercontent.com/7282254/143378392-430c1e79-22fb-49ae-afd9-c925e22806c9.png)

**Comment by kellyshang** [comment] 2021-11-25 07:52
Hi @tantommy , In order to further confirm the cause and for your privacy reasons, could you help export an `Extended Public Key` of your wallet and sent it to my mail: shangke@nervina.io ? Don't worry that the `Extended Public Key` won't allow anybody to do any transaction releated operations.
![image](https://user-images.githubusercontent.com/28836185/143401137-733c1f8c-3e89-44d3-9a5f-de913392a3db.png)

**Comment by tantommy** [comment] 2021-11-29 17:50
To recap:
@kellyshang has identified that because of a large amount of input/outputs when viewing the transaction details, the DB process gets locked up.

Conclusion:
Optimizations will be considered for a future release.

@kellyshang do we want to add this optimization to the backlog/board and close this issue for now?

**Comment by kellyshang** [comment] 2021-11-30 01:50
>@kellyshang do we want to add this optimization to the backlog/board and close this issue for now?

Yes, this optimization has been added to our backlog and we can close this issue for now. I will notify you when this issue been fixed.
Great thanks for your support.

**Closed by kellyshang** 2021-11-30 01:50 UTC
